spring.application.name=finanzas-backend
server.address=0.0.0.0

spring.datasource.url=jdbc:mysql://localhost:3307/finanzas_db
spring.datasource.username=finanzas_user
spring.datasource.password=finanzas_pass
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect

app.jwt.secret=una-clave-secreta-larga-y-dificil-de-adivinar-cambiala-luego-1234567890
app.jwt.expiration-ms=86400000

# Usando el nombre que espera GoogleTokenVerifierAdapter
google.oauth.client-id=819431523158-0g9svdjvpd4fnice4tgglgmvcvq5e28d.apps.googleusercontent.com